services:
  db:
    image: postgres:16
    container_name: q_database
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-mydb}
      POSTGRES_USER: ${POSTGRES_USER:-myuser}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-mypass}

    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - q_net
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-myuser} -d ${POSTGRES_DB:-mydb}"]
      interval: 5s
      retries: 5
      start_period: 5s

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: backend
    environment:
      NODE_ENV: development
      POSTGRES_USER: ${POSTGRES_USER:-myuser}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-mypass}
      POSTGRES_DB: ${POSTGRES_DB:-mydb}
      POSTGRES_HOST: db
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
    ports:
      - "3001:3000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - q_net
    volumes:
      - ./backend:/app
      - ./backend/node_modules:/app/node_modules
    working_dir: /app
    command: >
      sh -c "
      npx sequelize-cli db:migrate:undo:all &&
      npx sequelize-cli db:migrate &&
      npx sequelize-cli db:seed:all &&
      npm start
      "

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules

    working_dir: /app

    depends_on:
      - backend

    restart: unless-stopped
    networks:
      - q_net

  pgadmin:
    image: dpage/pgadmin4
    container_name: q_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
      PGADMIN_REPLACE_SERVERS_ON_STARTUP: "True"
      PGPASSFILE: /config/pgpass  
    
    configs:
      - source: pgadmin-pgpass
        target: /config/pgpass
        uid: "5050"
        gid: "5050"
        mode: 0400
      - source: pgadmin-servers
        target: /pgadmin4/servers.json
        mode: 0444

    ports:
      - "8081:80"
    networks:
      - q_net
    depends_on:
      db:
        condition: service_healthy

configs:
  pgadmin-servers:
    content: |
      {
        "Servers": {
          "1": {
            "Name": "QuantumTrader DB",
            "Group": "PostgreSQL",
            "Host": "db",
            "Port": 5432,
            "MaintenanceDB": "mydb",
            "Username": "myuser",
            "SSLMode": "prefer",
            "PassFile": "/config/pgpass"
          }
        }
      }
  pgadmin-pgpass:
    content: |
      db:5432:mydb:myuser:mypass

volumes:
  backend_node_modules:
  frontend_node_modules:
  pgdata:

networks:
  q_net:
