services:
  db:
    image: postgres:16
    container_name: q_database
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-mydb}
      POSTGRES_USER: ${POSTGRES_USER:-myuser}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-mypass}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - q_net
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-myuser}"]
      interval: 5s
      retries: 5
      start_period: 5s

  backend:
    build: ./backend
    container_name: backend
    environment:
      NODE_ENV: development
      POSTGRES_DB: ${POSTGRES_DB:-mydb}
      POSTGRES_USER: ${POSTGRES_USER:-myuser}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-mypass}
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - q_net
    volumes:
      - ./backend:/app
      - backend_node_modules:/app/node_modules

volumes:
  backend_node_modules:
  pgdata:

networks:
  q_net:
